using BMT.Contract.Logic;
using BMT.Database;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using BMT.Logic;
using BMT.Contract.Dtos;
using BMT.Database.Entity;
using BMT.Contract.Dtos.Results;

namespace BMT.Tests;


// NOTE - this entire class was generated by AI
public class BookLogicExtendedTests : IDisposable
{
    private readonly ServiceProvider _services;
    private readonly IBookLogic _sut;
    private readonly BmtDataContext _db;

    // Shared well-known ISBNs for seeded books
    private const string IsbnWithTwoCopies  = "978-0-13208-906-8"; // AvailableCopies = 2, TotalCopies = 2
    private const string IsbnWithOneCopy    = "0-13208-906-9";     // AvailableCopies = 1, TotalCopies = 1
    private const string IsbnFullyLent      = "978-3-16148-410-0"; // AvailableCopies = 0, TotalCopies = 1
    private const string IsbnUnused         = "178-0-13208-906-8"; // not in DB

    public BookLogicExtendedTests()
    {
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();

        var services = new ServiceCollection();
        services.AddDbContext<BmtDataContext>(options => options.UseSqlite(connection));
        services.RegisterLogicModule();
        _services = services.BuildServiceProvider();

        _db = _services.GetRequiredService<BmtDataContext>();
        _db.Database.EnsureCreated();
        Seed(_db);

        _sut = _services.GetRequiredService<IBookLogic>();
    }

    private void Seed(BmtDataContext ctx)
    {
        var author1 = new AuthorEntity { Id = Guid.NewGuid(), FullName = "Robert C. Martin" };
        var author2 = new AuthorEntity { Id = Guid.NewGuid(), FullName = "Evil Martin" };
        var author3 = new AuthorEntity { Id = Guid.NewGuid(), FullName = "Lone Author" };

        ctx.Authors.AddRange(author1, author2, author3);

        ctx.Books.AddRange(
            new BookEntity
            {
                Id = Guid.NewGuid(),
                Title = "Clean Code",
                Author = author1,
                Isbn = IsbnWithTwoCopies,
                AvailableCopies = 2,
                TotalCopies = 2,
                PublishDate = DateOnly.Parse("2007-01-01")
            },
            new BookEntity
            {
                Id = Guid.NewGuid(),
                Title = "Dirty Code",
                Author = author2,
                Isbn = IsbnWithOneCopy,
                AvailableCopies = 1,
                TotalCopies = 1,
                PublishDate = DateOnly.Parse("1666-12-16")
            },
            new BookEntity
            {
                Id = Guid.NewGuid(),
                Title = "Already Gone",
                Author = author3,
                Isbn = IsbnFullyLent,
                AvailableCopies = 0,
                TotalCopies = 1,
                PublishDate = DateOnly.Parse("2000-06-01")
            }
        );

        ctx.SaveChanges();
    }

    // -------------------------------------------------------------------------
    // LendBook
    // -------------------------------------------------------------------------

    [Fact]
    public async Task LendBook_DecreasesAvailableCopies()
    {
        var result = await _sut.LendBook(IsbnWithTwoCopies);

        Assert.True(result.IsSuccess);
        Assert.Equal(1, result.Payload);
    }

    [Fact]
    public async Task LendBook_CreatesTransactionRecord()
    {
        await _sut.LendBook(IsbnWithTwoCopies);

        var transaction = _db.Transactions
            .OrderByDescending(t => t.DateTime)
            .FirstOrDefault();

        Assert.NotNull(transaction);
        Assert.False(transaction!.IsReturn);
    }

    [Fact]
    public async Task LendBook_LendAllCopies_AvailableReachesZero()
    {
        await _sut.LendBook(IsbnWithOneCopy);
        var result = await _sut.LendBook(IsbnWithOneCopy);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    [Fact]
    public async Task LendBook_WhenNoCopiesAvailable_ReturnsBadRequest()
    {
        var result = await _sut.LendBook(IsbnFullyLent);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    [Fact]
    public async Task LendBook_WithNonexistentIsbn_ReturnsBadRequest()
    {
        var result = await _sut.LendBook(IsbnUnused);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.NotFound, result.Error!.Code);
    }

    [Theory]
    [InlineData("not-an-isbn")]
    [InlineData("")]
    [InlineData("978-0-13208-906-XYZ")]
    public async Task LendBook_WithInvalidIsbnFormat_ReturnsBadRequest(string isbn)
    {
        var result = await _sut.LendBook(isbn);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    // -------------------------------------------------------------------------
    // ReturnBook
    // -------------------------------------------------------------------------

    [Fact]
    public async Task ReturnBook_IncreasesAvailableCopies()
    {
        // Lend first so there's something to return
        await _sut.LendBook(IsbnWithTwoCopies);

        var result = await _sut.ReturnBook(IsbnWithTwoCopies);

        Assert.True(result.IsSuccess);
        Assert.Equal(2, result.Payload);
    }

    [Fact]
    public async Task ReturnBook_CreatesTransactionRecord()
    {
        await _sut.LendBook(IsbnWithTwoCopies);
        await _sut.ReturnBook(IsbnWithTwoCopies);

        var transaction = _db.Transactions
            .OrderByDescending(t => t.DateTime)
            .FirstOrDefault();

        Assert.NotNull(transaction);
        Assert.True(transaction!.IsReturn);
    }

    [Fact]
    public async Task ReturnBook_WhenAllCopiesAlreadyReturned_ReturnsBadRequest()
    {
        // IsbnWithTwoCopies starts fully available — returning without lending should fail
        var result = await _sut.ReturnBook(IsbnWithTwoCopies);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    [Fact]
    public async Task ReturnBook_WithNonexistentIsbn_ReturnsBadRequest()
    {
        var result = await _sut.ReturnBook(IsbnUnused);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.NotFound, result.Error!.Code);
    }

    [Theory]
    [InlineData("not-an-isbn")]
    [InlineData("")]
    [InlineData("978-0-13208-906-XYZ")]
    public async Task ReturnBook_WithInvalidIsbnFormat_ReturnsBadRequest(string isbn)
    {
        var result = await _sut.ReturnBook(isbn);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    [Fact]
    public async Task LendAndReturn_MultipleRoundTrips_MaintainsCorrectCount()
    {
        await _sut.LendBook(IsbnWithTwoCopies);
        await _sut.LendBook(IsbnWithTwoCopies);
        await _sut.ReturnBook(IsbnWithTwoCopies);
        var result = await _sut.ReturnBook(IsbnWithTwoCopies);

        Assert.True(result.IsSuccess);
        Assert.Equal(2, result.Payload); // back to original
    }

    // -------------------------------------------------------------------------
    // GetBookTransactionHistory
    // -------------------------------------------------------------------------

    [Fact]
    public async Task GetBookTransactionHistory_ReturnsEmpty_WhenNoTransactions()
    {
        var result = await _sut.GetBookTransactionHistory();

        Assert.True(result.IsSuccess);
        Assert.Empty(result.Payload!);
    }

    [Fact]
    public async Task GetBookTransactionHistory_ReturnsTransactionsOrderedByDateDescending()
    {
        await _sut.LendBook(IsbnWithTwoCopies);
        await _sut.LendBook(IsbnWithOneCopy);
        await _sut.ReturnBook(IsbnWithTwoCopies);

        var result = await _sut.GetBookTransactionHistory();

        Assert.True(result.IsSuccess);
        Assert.Equal(3, result.Payload!.Count);

        // Verify descending order
        var dates = result.Payload!.Select(t => t.DateTime).ToList();
        Assert.Equal(dates.OrderByDescending(d => d).ToList(), dates);
    }

    [Fact]
    public async Task GetBookTransactionHistory_RecordsLendAndReturn_WithCorrectFlags()
    {
        await _sut.LendBook(IsbnWithOneCopy);
        await _sut.ReturnBook(IsbnWithOneCopy);

        var result = await _sut.GetBookTransactionHistory();
        Assert.True(result.IsSuccess);

        // Most recent is the return
        Assert.True(result.Payload![0].IsReturn);
        Assert.False(result.Payload![1].IsReturn);
    }

    // -------------------------------------------------------------------------
    // CreateBook — author scenarios
    // -------------------------------------------------------------------------

    [Fact]
    public async Task CreateBook_WithNewAuthor_CreatesAuthorAndBook()
    {
        var newBook = new BookDto
        {
            Title = "New Book",
            Author = "Brand New Author",
            Isbn = IsbnUnused,
            AvailableCopies = 3,
            PublishDate = DateOnly.Parse("2020-01-01")
        };

        var result = await _sut.CreateBook(newBook);

        Assert.True(result.IsSuccess);
        Assert.True(_db.Authors.Any(a => a.FullName == "Brand New Author"
                                      || a.FullName == "brand new author")); // depending on NormalizeFullName
    }

    [Fact]
    public async Task CreateBook_WithExistingAuthorName_DoesNotDuplicateAuthor()
    {
        var authorCountBefore = _db.Authors.Count();

        var newBook = new BookDto
        {
            Title = "Another Martin Book",
            Author = "Robert C. Martin", // already seeded
            Isbn = IsbnUnused,
            AvailableCopies = 1,
            PublishDate = DateOnly.Parse("2022-05-10")
        };

        var result = await _sut.CreateBook(newBook);

        Assert.True(result.IsSuccess);
        Assert.Equal(authorCountBefore, _db.Authors.Count()); // no new author row
    }

    [Fact]
    public async Task CreateBook_SetsAvailableAndTotalCopiesToSameValue()
    {
        var newBook = new BookDto
        {
            Title = "Fresh Off The Press",
            Author = "A New Writer",
            Isbn = IsbnUnused,
            AvailableCopies = 7,
            PublishDate = DateOnly.Parse("2023-03-15")
        };

        var result = await _sut.CreateBook(newBook);
        Assert.True(result.IsSuccess);

        var entity = _db.Books.First(b => b.Id == result.Payload);
        Assert.Equal(7, entity.AvailableCopies);
        Assert.Equal(7, entity.TotalCopies);
    }

    [Fact]
    public async Task CreateBook_WithDuplicateIsbn_ReturnsBadRequest()
    {
        var duplicate = new BookDto
        {
            Title = "Some Title",
            Author = "Some Author",
            Isbn = IsbnWithTwoCopies, // already seeded
            AvailableCopies = 1,
            PublishDate = DateOnly.Parse("2020-01-01")
        };

        var result = await _sut.CreateBook(duplicate);

        Assert.False(result.IsSuccess);
        Assert.Equal(ErrorCode.BadRequest, result.Error!.Code);
    }

    [Fact]
    public async Task CreateBook_Success_CanBeRetrievedByIsbn()
    {
        var newBook = new BookDto
        {
            Title = "Findable Book",
            Author = "Findable Author",
            Isbn = IsbnUnused,
            AvailableCopies = 2,
            PublishDate = DateOnly.Parse("2021-08-20")
        };

        var createResult = await _sut.CreateBook(newBook);
        Assert.True(createResult.IsSuccess);

        var fetchResult = await _sut.GetBookByISBN(IsbnUnused);
        Assert.True(fetchResult.IsSuccess);
        Assert.Equal("Findable Book", fetchResult.Payload!.Title);
    }

    // -------------------------------------------------------------------------
    // GetSecurity (trivial, but worth covering)
    // -------------------------------------------------------------------------

    [Fact]
    public async Task GetSecurity_ReturnsSuccess()
    {
        var result = await _sut.GetSecurity();

        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Payload);
    }

    public void Dispose() => _services.Dispose();
}